import { Nurse } from '@/types/nurse';

export const mockNurses: Nurse[] = [
  {
    id: 1,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ThandiweMokoena',
    fullName: 'Thandiwe Mokoena',
    preferredName: 'Thandi',
    pipelineStage: 'Placed',
    nextAction: 'Schedule Check-in',
    readinessStatus: 'Placed',
    flagCount: 0,
    lastContacted: new Date('2024-11-15'),
    cohort: 'Cohort 2024-A',
    submittedAt: new Date('2024-01-10'),
    email: 'thandiwe.mokoena@email.co.za',
    contactNumber: '+27 82 456 7890',
    gender: 'Female',
    ageGroup: '30-35',
    provinceCity: 'Gauteng, Johannesburg',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2018-45672',
    sancApcExpiry: new Date('2025-03-31'),
    sancApcStatus: 'Current',
    highestQualification: 'Bachelor of Nursing',
    institution: 'University of Witwatersrand',
    yearsExperience: 8,
    primaryClinicalSpecialty: 'ICU',
    additionalCertifications: 'Critical Care Certificate, ACLS',
    employmentStatus: 'Employed',
    currentEmployer: 'Charlotte Maxeke Hospital',
    validPassport: true,
    passportExpiry: new Date('2029-06-15'),
    previouslyTakenTest: true,
    efSetScore: 72,
    efSetLevel: 'C1',
    englishPts: 9,
    proficiencyLevel: 'Advanced',
    oetStatus: 'Passed',
    oetExamDate: new Date('2024-05-20'),
    oetExamCentre: 'Johannesburg',
    oetWriting: 380,
    oetSpeaking: 400,
    oetListening: 390,
    oetReading: 370,
    oetOverallResult: 'B',
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 9,
    sancStatusScore: 10,
    englishProficiency: 9,
    qualifications: 8,
    specialisation: 9,
    validPassportScore: 10,
    financialReadiness: 8,
    motivationScore: 9,
    cvScore: 8.5,
    finalScore: 82,
    tier: 'Tier 1',
    shortlistDecision: 'Yes',
    firstInterviewDate: new Date('2024-02-15'),
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: 'Cohort 2024-A',
    agreementSent: true,
    agreementSentDate: new Date('2024-03-01'),
    agreementSigned: true,
    agreementSignedDate: new Date('2024-03-05'),
    commitmentFeeStatus: 'Paid',
    commitmentFeeDate: new Date('2024-03-10'),
    placementStatus: 'Placed',
    destinationCountry: 'United Kingdom',
    employer: 'NHS Trust - Royal London Hospital',
    placementDate: new Date('2024-09-01'),
    placementFeeInvoiced: true,
    placementFeeReceived: true,
    motivations: 'Seeking better career growth and international experience in critical care.',
    questions: null,
    notesFlags: null,
    source: 'Website',
    sourceRecord: 'WEB-2024-001',
    communicationLog: '2024-01-10: Application received. 2024-02-15: Interview completed. 2024-03-01: Agreement sent. 2024-09-01: Placement confirmed.',
  },
  {
    id: 2,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=NomfundoNdlovu',
    fullName: 'Nomfundo Ndlovu',
    preferredName: 'Nomie',
    pipelineStage: 'Training Active',
    nextAction: 'Register for OET',
    readinessStatus: 'Not Ready',
    flagCount: 0,
    lastContacted: new Date('2024-11-20'),
    cohort: 'Cohort 2024-B',
    submittedAt: new Date('2024-03-22'),
    email: 'nomfundo.ndlovu@email.co.za',
    contactNumber: '+27 73 234 5678',
    gender: 'Female',
    ageGroup: '25-30',
    provinceCity: 'KwaZulu-Natal, Durban',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2020-78341',
    sancApcExpiry: new Date('2025-06-30'),
    sancApcStatus: 'Current',
    highestQualification: 'Diploma in Nursing',
    institution: 'Durban University of Technology',
    yearsExperience: 4,
    primaryClinicalSpecialty: 'Paediatrics',
    additionalCertifications: 'Paediatric Advanced Life Support',
    employmentStatus: 'Employed',
    currentEmployer: 'Inkosi Albert Luthuli Hospital',
    validPassport: true,
    passportExpiry: new Date('2028-11-20'),
    previouslyTakenTest: true,
    efSetScore: 58,
    efSetLevel: 'B2',
    englishPts: 7,
    proficiencyLevel: 'Upper Intermediate',
    oetStatus: 'Not Registered',
    oetExamDate: null,
    oetExamCentre: null,
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 5,
    sancStatusScore: 10,
    englishProficiency: 7,
    qualifications: 6,
    specialisation: 7,
    validPassportScore: 10,
    financialReadiness: 6,
    motivationScore: 8,
    cvScore: 7.0,
    finalScore: 59,
    tier: 'Tier 2',
    shortlistDecision: 'Yes',
    firstInterviewDate: new Date('2024-04-20'),
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: 'Cohort 2024-B',
    agreementSent: true,
    agreementSentDate: new Date('2024-05-10'),
    agreementSigned: true,
    agreementSignedDate: new Date('2024-05-15'),
    commitmentFeeStatus: 'Paid',
    commitmentFeeDate: new Date('2024-05-20'),
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Want to provide my children with better opportunities abroad.',
    questions: 'What support is provided for families?',
    notesFlags: null,
    source: 'Referral',
    sourceRecord: 'REF-2024-015',
    communicationLog: '2024-03-22: Application received. 2024-04-20: Interview completed. 2024-05-10: Agreement sent.',
  },
  {
    id: 3,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=SiphoMkhize',
    fullName: 'Sipho Mkhize',
    preferredName: null,
    pipelineStage: 'Shortlisted -- Yes',
    nextAction: 'Send Agreement',
    readinessStatus: 'Not Ready',
    flagCount: 2,
    lastContacted: new Date('2024-11-01'),
    cohort: null,
    submittedAt: new Date('2024-06-15'),
    email: 'sipho.mkhize@email.co.za',
    contactNumber: '+27 84 567 8901',
    gender: 'Male',
    ageGroup: '35-40',
    provinceCity: 'Gauteng, Pretoria',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2015-23456',
    sancApcExpiry: new Date('2024-12-31'),
    sancApcStatus: 'Expiring Soon',
    highestQualification: 'Bachelor of Nursing',
    institution: 'University of Pretoria',
    yearsExperience: 12,
    primaryClinicalSpecialty: 'Emergency',
    additionalCertifications: 'Trauma Nursing, ACLS, BLS Instructor',
    employmentStatus: 'Employed',
    currentEmployer: 'Steve Biko Academic Hospital',
    validPassport: true,
    passportExpiry: new Date('2026-02-28'),
    previouslyTakenTest: true,
    efSetScore: 65,
    efSetLevel: 'B2',
    englishPts: 8,
    proficiencyLevel: 'Upper Intermediate',
    oetStatus: null,
    oetExamDate: null,
    oetExamCentre: null,
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 10,
    sancStatusScore: 8,
    englishProficiency: 8,
    qualifications: 8,
    specialisation: 8,
    validPassportScore: 10,
    financialReadiness: 5,
    motivationScore: 7,
    cvScore: 8.0,
    finalScore: 64,
    tier: 'Tier 1',
    shortlistDecision: 'Yes',
    firstInterviewDate: new Date('2024-07-20'),
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: null,
    agreementSent: false,
    agreementSentDate: null,
    agreementSigned: false,
    agreementSignedDate: null,
    commitmentFeeStatus: null,
    commitmentFeeDate: null,
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Looking for higher earning potential and professional development.',
    questions: 'Can my SANC registration be renewed while abroad?',
    notesFlags: 'SANC APC expiring soon - needs renewal. Financial readiness concerns flagged.',
    source: 'Social Media',
    sourceRecord: 'SM-2024-042',
    communicationLog: '2024-06-15: Application received. 2024-07-20: Interview completed. 2024-11-01: Follow-up call - SANC renewal discussed.',
  },
  {
    id: 4,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=LindiweVanDerMerwe',
    fullName: 'Lindiwe van der Merwe',
    preferredName: 'Lindi',
    pipelineStage: 'Under Review',
    nextAction: 'Review CV',
    readinessStatus: 'Not Ready',
    flagCount: 0,
    lastContacted: new Date('2024-11-18'),
    cohort: null,
    submittedAt: new Date('2024-10-05'),
    email: 'lindiwe.vdm@email.co.za',
    contactNumber: '+27 61 890 1234',
    gender: 'Female',
    ageGroup: '25-30',
    provinceCity: 'Western Cape, Cape Town',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2021-56789',
    sancApcExpiry: new Date('2025-09-30'),
    sancApcStatus: 'Current',
    highestQualification: 'Diploma in Nursing',
    institution: 'University of the Western Cape',
    yearsExperience: 3,
    primaryClinicalSpecialty: 'Maternity',
    additionalCertifications: 'Midwifery Certificate',
    employmentStatus: 'Employed',
    currentEmployer: 'Groote Schuur Hospital',
    validPassport: true,
    passportExpiry: new Date('2030-01-15'),
    previouslyTakenTest: true,
    efSetScore: 70,
    efSetLevel: 'C1',
    englishPts: 9,
    proficiencyLevel: 'Advanced',
    oetStatus: null,
    oetExamDate: null,
    oetExamCentre: null,
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 4,
    sancStatusScore: 10,
    englishProficiency: 9,
    qualifications: 6,
    specialisation: 7,
    validPassportScore: 10,
    financialReadiness: 7,
    motivationScore: 8,
    cvScore: 7.5,
    finalScore: 61,
    tier: 'Tier 2',
    shortlistDecision: null,
    firstInterviewDate: null,
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: null,
    agreementSent: false,
    agreementSentDate: null,
    agreementSigned: false,
    agreementSignedDate: null,
    commitmentFeeStatus: null,
    commitmentFeeDate: null,
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Passionate about maternity care and wants to learn from world-class facilities.',
    questions: 'Is midwifery experience valued in the UK?',
    notesFlags: null,
    source: 'Website',
    sourceRecord: 'WEB-2024-089',
    communicationLog: '2024-10-05: Application received. 2024-11-18: CV review in progress.',
  },
  {
    id: 5,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=BonganiDlamini',
    fullName: 'Bongani Dlamini',
    preferredName: 'Bongs',
    pipelineStage: 'Dropped Out',
    nextAction: null,
    readinessStatus: 'Dropped Out',
    flagCount: 1,
    lastContacted: new Date('2024-08-10'),
    cohort: 'Cohort 2024-A',
    submittedAt: new Date('2024-01-20'),
    email: 'bongani.dlamini@email.co.za',
    contactNumber: '+27 79 345 6789',
    gender: 'Male',
    ageGroup: '40-45',
    provinceCity: 'Eastern Cape, East London',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2010-12345',
    sancApcExpiry: new Date('2025-03-31'),
    sancApcStatus: 'Current',
    highestQualification: 'Master of Nursing',
    institution: 'University of Fort Hare',
    yearsExperience: 15,
    primaryClinicalSpecialty: 'General',
    additionalCertifications: 'Nursing Management, HIV/AIDS Counselling',
    employmentStatus: 'Employed',
    currentEmployer: 'Frere Hospital',
    validPassport: false,
    passportExpiry: null,
    previouslyTakenTest: true,
    efSetScore: 55,
    efSetLevel: 'B2',
    englishPts: 6,
    proficiencyLevel: 'Upper Intermediate',
    oetStatus: null,
    oetExamDate: null,
    oetExamCentre: null,
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 10,
    sancStatusScore: 10,
    englishProficiency: 6,
    qualifications: 10,
    specialisation: 5,
    validPassportScore: 0,
    financialReadiness: 4,
    motivationScore: 6,
    cvScore: 7.0,
    finalScore: 51,
    tier: 'Tier 2',
    shortlistDecision: 'Yes',
    firstInterviewDate: new Date('2024-02-25'),
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: 'Cohort 2024-A',
    agreementSent: true,
    agreementSentDate: new Date('2024-03-15'),
    agreementSigned: true,
    agreementSignedDate: new Date('2024-03-20'),
    commitmentFeeStatus: 'Refunded',
    commitmentFeeDate: new Date('2024-03-25'),
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Family decided against relocation.',
    questions: null,
    notesFlags: 'Dropped out due to family circumstances. Passport application not completed.',
    source: 'Referral',
    sourceRecord: 'REF-2024-003',
    communicationLog: '2024-01-20: Application received. 2024-02-25: Interview completed. 2024-08-10: Confirmed withdrawal from programme.',
  },
  {
    id: 6,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ZaneleNkosi',
    fullName: 'Zanele Nkosi',
    preferredName: 'Zee',
    pipelineStage: 'Deferred',
    nextAction: 'Schedule Check-in',
    readinessStatus: 'Deferred',
    flagCount: 0,
    lastContacted: new Date('2024-10-25'),
    cohort: 'Cohort 2024-B',
    submittedAt: new Date('2024-04-12'),
    email: 'zanele.nkosi@email.co.za',
    contactNumber: '+27 83 678 9012',
    gender: 'Female',
    ageGroup: '30-35',
    provinceCity: 'Limpopo, Polokwane',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2017-34567',
    sancApcExpiry: new Date('2025-06-30'),
    sancApcStatus: 'Current',
    highestQualification: 'Bachelor of Nursing',
    institution: 'University of Limpopo',
    yearsExperience: 7,
    primaryClinicalSpecialty: 'Oncology',
    additionalCertifications: 'Chemotherapy Administration, Palliative Care',
    employmentStatus: 'Employed',
    currentEmployer: 'Pietersburg Hospital',
    validPassport: true,
    passportExpiry: new Date('2027-08-20'),
    previouslyTakenTest: true,
    efSetScore: 62,
    efSetLevel: 'B2',
    englishPts: 7,
    proficiencyLevel: 'Upper Intermediate',
    oetStatus: 'Registered',
    oetExamDate: new Date('2025-02-15'),
    oetExamCentre: 'Johannesburg',
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 7,
    sancStatusScore: 10,
    englishProficiency: 7,
    qualifications: 8,
    specialisation: 8,
    validPassportScore: 10,
    financialReadiness: 6,
    motivationScore: 7,
    cvScore: 7.5,
    finalScore: 63,
    tier: 'Tier 2',
    shortlistDecision: 'Yes',
    firstInterviewDate: new Date('2024-05-18'),
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: 'Cohort 2024-B',
    agreementSent: true,
    agreementSentDate: new Date('2024-06-01'),
    agreementSigned: true,
    agreementSignedDate: new Date('2024-06-05'),
    commitmentFeeStatus: 'Paid',
    commitmentFeeDate: new Date('2024-06-10'),
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Specialise in oncology nursing abroad. Deferred due to pregnancy.',
    questions: 'Can I resume after maternity leave?',
    notesFlags: 'Deferred to Cohort 2025-A due to pregnancy. Expected return April 2025.',
    source: 'Website',
    sourceRecord: 'WEB-2024-034',
    communicationLog: '2024-04-12: Application received. 2024-05-18: Interview. 2024-10-25: Deferral confirmed - pregnancy.',
  },
  {
    id: 7,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=PreciousMaila',
    fullName: 'Precious Maila',
    preferredName: null,
    pipelineStage: 'OET Registered',
    nextAction: 'Confirm OET Results',
    readinessStatus: 'Not Ready',
    flagCount: 0,
    lastContacted: new Date('2024-11-22'),
    cohort: 'Cohort 2024-B',
    submittedAt: new Date('2024-04-01'),
    email: 'precious.maila@email.co.za',
    contactNumber: '+27 76 012 3456',
    gender: 'Female',
    ageGroup: '25-30',
    provinceCity: 'Gauteng, Soweto',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2021-89012',
    sancApcExpiry: new Date('2025-09-30'),
    sancApcStatus: 'Current',
    highestQualification: 'Diploma in Nursing',
    institution: 'Chris Hani Baragwanath Nursing College',
    yearsExperience: 3,
    primaryClinicalSpecialty: 'ICU',
    additionalCertifications: 'Critical Care Certificate',
    employmentStatus: 'Employed',
    currentEmployer: 'Chris Hani Baragwanath Hospital',
    validPassport: true,
    passportExpiry: new Date('2029-03-10'),
    previouslyTakenTest: true,
    efSetScore: 60,
    efSetLevel: 'B2',
    englishPts: 7,
    proficiencyLevel: 'Upper Intermediate',
    oetStatus: 'Registered',
    oetExamDate: new Date('2024-12-07'),
    oetExamCentre: 'Johannesburg',
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 4,
    sancStatusScore: 10,
    englishProficiency: 7,
    qualifications: 6,
    specialisation: 9,
    validPassportScore: 10,
    financialReadiness: 7,
    motivationScore: 9,
    cvScore: 7.0,
    finalScore: 62,
    tier: 'Tier 2',
    shortlistDecision: 'Yes',
    firstInterviewDate: new Date('2024-05-10'),
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: 'Cohort 2024-B',
    agreementSent: true,
    agreementSentDate: new Date('2024-05-25'),
    agreementSigned: true,
    agreementSignedDate: new Date('2024-05-30'),
    commitmentFeeStatus: 'Paid',
    commitmentFeeDate: new Date('2024-06-05'),
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Gain international ICU experience and send money home to family.',
    questions: 'How soon after OET can placement begin?',
    notesFlags: null,
    source: 'Career Fair',
    sourceRecord: 'CF-2024-008',
    communicationLog: '2024-04-01: Application via career fair. 2024-05-10: Interview. 2024-11-22: OET registration confirmed for Dec.',
  },
  {
    id: 8,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ThaboModise',
    fullName: 'Thabo Modise',
    preferredName: null,
    pipelineStage: 'Applied',
    nextAction: 'Request CV',
    readinessStatus: 'Not Ready',
    flagCount: 0,
    lastContacted: null,
    cohort: null,
    submittedAt: new Date('2024-11-20'),
    email: 'thabo.modise@email.co.za',
    contactNumber: '+27 72 456 7890',
    gender: 'Male',
    ageGroup: '30-35',
    provinceCity: 'Free State, Bloemfontein',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2019-67890',
    sancApcExpiry: new Date('2025-12-31'),
    sancApcStatus: 'Current',
    highestQualification: 'Diploma in Nursing',
    institution: 'Central University of Technology',
    yearsExperience: 5,
    primaryClinicalSpecialty: 'General',
    additionalCertifications: null,
    employmentStatus: 'Employed',
    currentEmployer: 'Universitas Academic Hospital',
    validPassport: false,
    passportExpiry: null,
    previouslyTakenTest: false,
    efSetScore: null,
    efSetLevel: null,
    englishPts: null,
    proficiencyLevel: null,
    oetStatus: null,
    oetExamDate: null,
    oetExamCentre: null,
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 5,
    sancStatusScore: 10,
    englishProficiency: 0,
    qualifications: 6,
    specialisation: 5,
    validPassportScore: 0,
    financialReadiness: 5,
    motivationScore: 6,
    cvScore: null,
    finalScore: null,
    tier: null,
    shortlistDecision: null,
    firstInterviewDate: null,
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: null,
    agreementSent: false,
    agreementSentDate: null,
    agreementSigned: false,
    agreementSignedDate: null,
    commitmentFeeStatus: null,
    commitmentFeeDate: null,
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Want to explore opportunities abroad.',
    questions: 'What are the requirements to qualify?',
    notesFlags: null,
    source: 'Social Media',
    sourceRecord: 'SM-2024-098',
    communicationLog: '2024-11-20: Application received via social media ad.',
  },
  {
    id: 9,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=AyandaMaseko',
    fullName: 'Ayanda Maseko',
    preferredName: 'Aya',
    pipelineStage: 'CV + English Submitted',
    nextAction: 'Review EfSet Results',
    readinessStatus: 'Not Ready',
    flagCount: 0,
    lastContacted: new Date('2024-11-12'),
    cohort: null,
    submittedAt: new Date('2024-09-28'),
    email: 'ayanda.maseko@email.co.za',
    contactNumber: '+27 81 234 5678',
    gender: 'Female',
    ageGroup: '25-30',
    provinceCity: 'Gauteng, Johannesburg',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2022-01234',
    sancApcExpiry: new Date('2025-12-31'),
    sancApcStatus: 'Current',
    highestQualification: 'Diploma in Nursing',
    institution: 'University of Johannesburg',
    yearsExperience: 2,
    primaryClinicalSpecialty: 'Maternity',
    additionalCertifications: 'Basic Midwifery',
    employmentStatus: 'Employed',
    currentEmployer: 'Rahima Moosa Hospital',
    validPassport: true,
    passportExpiry: new Date('2030-05-20'),
    previouslyTakenTest: true,
    efSetScore: 52,
    efSetLevel: 'B1',
    englishPts: 5,
    proficiencyLevel: 'Intermediate',
    oetStatus: null,
    oetExamDate: null,
    oetExamCentre: null,
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 3,
    sancStatusScore: 10,
    englishProficiency: 5,
    qualifications: 6,
    specialisation: 7,
    validPassportScore: 10,
    financialReadiness: 6,
    motivationScore: 8,
    cvScore: 6.5,
    finalScore: 55,
    tier: 'Tier 3',
    shortlistDecision: null,
    firstInterviewDate: null,
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: null,
    agreementSent: false,
    agreementSentDate: null,
    agreementSigned: false,
    agreementSignedDate: null,
    commitmentFeeStatus: null,
    commitmentFeeDate: null,
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Improve English and gain midwifery experience in the UK.',
    questions: 'Are there English classes provided as part of the programme?',
    notesFlags: null,
    source: 'Website',
    sourceRecord: 'WEB-2024-072',
    communicationLog: '2024-09-28: Application received. 2024-11-12: EfSet results received - B1 level.',
  },
  {
    id: 10,
    profilePhoto: null,
    fullName: 'Kagiso Molefe',
    preferredName: 'Kagi',
    pipelineStage: 'Not Selected',
    nextAction: null,
    readinessStatus: 'Not Selected',
    flagCount: 0,
    lastContacted: new Date('2024-09-15'),
    cohort: null,
    submittedAt: new Date('2024-07-01'),
    email: 'kagiso.molefe@email.co.za',
    contactNumber: '+27 64 789 0123',
    gender: 'Male',
    ageGroup: '20-25',
    provinceCity: 'Western Cape, Stellenbosch',
    sancRegistered: false,
    rnInSA: false,
    sancNumber: null,
    sancApcExpiry: null,
    sancApcStatus: 'Not Registered',
    highestQualification: 'Enrolled Nurse Certificate',
    institution: 'Stellenbosch Academy of Health',
    yearsExperience: 1,
    primaryClinicalSpecialty: 'General',
    additionalCertifications: null,
    employmentStatus: 'Employed',
    currentEmployer: 'Tygerberg Hospital',
    validPassport: false,
    passportExpiry: null,
    previouslyTakenTest: false,
    efSetScore: null,
    efSetLevel: null,
    englishPts: null,
    proficiencyLevel: null,
    oetStatus: null,
    oetExamDate: null,
    oetExamCentre: null,
    oetWriting: null,
    oetSpeaking: null,
    oetListening: null,
    oetReading: null,
    oetOverallResult: null,
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 1,
    sancStatusScore: 0,
    englishProficiency: 0,
    qualifications: 3,
    specialisation: 3,
    validPassportScore: 0,
    financialReadiness: 3,
    motivationScore: 5,
    cvScore: 4.0,
    finalScore: 15,
    tier: 'Tier 3',
    shortlistDecision: 'No',
    firstInterviewDate: null,
    nonSelectionReason: 'Does not meet minimum requirements - not SANC registered as RN.',
    recommendedPathway: 'Complete RN qualification first, then reapply.',
    cohortAssigned: null,
    agreementSent: false,
    agreementSentDate: null,
    agreementSigned: false,
    agreementSignedDate: null,
    commitmentFeeStatus: null,
    commitmentFeeDate: null,
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Interested in working abroad but still completing qualifications.',
    questions: null,
    notesFlags: null,
    source: 'Website',
    sourceRecord: 'WEB-2024-055',
    communicationLog: '2024-07-01: Application received. 2024-09-15: Rejection email sent with pathway recommendation.',
  },
  {
    id: 11,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=FatimaPatrick',
    fullName: 'Fatima Patrick',
    preferredName: null,
    pipelineStage: 'Placement Ready',
    nextAction: 'Begin Placement Matching',
    readinessStatus: 'Placement Ready',
    flagCount: 0,
    lastContacted: new Date('2024-11-25'),
    cohort: 'Cohort 2024-A',
    submittedAt: new Date('2024-01-15'),
    email: 'fatima.patrick@email.co.za',
    contactNumber: '+27 82 901 2345',
    gender: 'Female',
    ageGroup: '30-35',
    provinceCity: 'KwaZulu-Natal, Pietermaritzburg',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2018-90123',
    sancApcExpiry: new Date('2025-06-30'),
    sancApcStatus: 'Current',
    highestQualification: 'Bachelor of Nursing',
    institution: 'University of KwaZulu-Natal',
    yearsExperience: 6,
    primaryClinicalSpecialty: 'Paediatrics',
    additionalCertifications: 'Paediatric ICU, PALS',
    employmentStatus: 'Resigned',
    currentEmployer: null,
    validPassport: true,
    passportExpiry: new Date('2029-09-30'),
    previouslyTakenTest: true,
    efSetScore: 75,
    efSetLevel: 'C1',
    englishPts: 9,
    proficiencyLevel: 'Advanced',
    oetStatus: 'Passed',
    oetExamDate: new Date('2024-08-10'),
    oetExamCentre: 'Durban',
    oetWriting: 400,
    oetSpeaking: 420,
    oetListening: 380,
    oetReading: 390,
    oetOverallResult: 'B',
    oetRetakeRequired: false,
    oetRetakeComponents: null,
    hospitalExp: 7,
    sancStatusScore: 10,
    englishProficiency: 9,
    qualifications: 8,
    specialisation: 9,
    validPassportScore: 10,
    financialReadiness: 9,
    motivationScore: 10,
    cvScore: 8.5,
    finalScore: 82,
    tier: 'Tier 1',
    shortlistDecision: 'Yes',
    firstInterviewDate: new Date('2024-02-20'),
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: 'Cohort 2024-A',
    agreementSent: true,
    agreementSentDate: new Date('2024-03-05'),
    agreementSigned: true,
    agreementSignedDate: new Date('2024-03-08'),
    commitmentFeeStatus: 'Paid',
    commitmentFeeDate: new Date('2024-03-12'),
    placementStatus: 'Matching',
    destinationCountry: 'United Kingdom',
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Passionate about paediatric care. Wants to work in a children hospital.',
    questions: 'Are there opportunities specifically in paediatric hospitals?',
    notesFlags: null,
    source: 'Referral',
    sourceRecord: 'REF-2024-005',
    communicationLog: '2024-01-15: Application received. 2024-02-20: Interview. 2024-08-10: OET passed. 2024-11-25: Placement matching started.',
  },
  {
    id: 12,
    profilePhoto: 'https://api.dicebear.com/7.x/avataaars/svg?seed=GraceOkonkwo',
    fullName: 'Grace Okonkwo',
    preferredName: null,
    pipelineStage: 'OET Failed',
    nextAction: 'Schedule OET Retake',
    readinessStatus: 'Not Ready',
    flagCount: 1,
    lastContacted: new Date('2024-11-10'),
    cohort: 'Cohort 2024-B',
    submittedAt: new Date('2024-03-30'),
    email: 'grace.okonkwo@email.co.za',
    contactNumber: '+27 71 567 8901',
    gender: 'Female',
    ageGroup: '35-40',
    provinceCity: 'Gauteng, Johannesburg',
    sancRegistered: true,
    rnInSA: true,
    sancNumber: 'SANC-2016-45678',
    sancApcExpiry: new Date('2025-03-31'),
    sancApcStatus: 'Current',
    highestQualification: 'Bachelor of Nursing',
    institution: 'University of Johannesburg',
    yearsExperience: 9,
    primaryClinicalSpecialty: 'Emergency',
    additionalCertifications: 'Trauma Nursing, Emergency Care',
    employmentStatus: 'Employed',
    currentEmployer: 'Helen Joseph Hospital',
    validPassport: true,
    passportExpiry: new Date('2028-07-15'),
    previouslyTakenTest: true,
    efSetScore: 56,
    efSetLevel: 'B2',
    englishPts: 6,
    proficiencyLevel: 'Upper Intermediate',
    oetStatus: 'Failed',
    oetExamDate: new Date('2024-10-12'),
    oetExamCentre: 'Johannesburg',
    oetWriting: 290,
    oetSpeaking: 350,
    oetListening: 320,
    oetReading: 310,
    oetOverallResult: 'C+',
    oetRetakeRequired: true,
    oetRetakeComponents: 'Writing',
    hospitalExp: 8,
    sancStatusScore: 10,
    englishProficiency: 6,
    qualifications: 8,
    specialisation: 8,
    validPassportScore: 10,
    financialReadiness: 7,
    motivationScore: 8,
    cvScore: 7.5,
    finalScore: 65,
    tier: 'Tier 2',
    shortlistDecision: 'Yes',
    firstInterviewDate: new Date('2024-05-05'),
    nonSelectionReason: null,
    recommendedPathway: null,
    cohortAssigned: 'Cohort 2024-B',
    agreementSent: true,
    agreementSentDate: new Date('2024-05-20'),
    agreementSigned: true,
    agreementSignedDate: new Date('2024-05-25'),
    commitmentFeeStatus: 'Paid',
    commitmentFeeDate: new Date('2024-05-30'),
    placementStatus: null,
    destinationCountry: null,
    employer: null,
    placementDate: null,
    placementFeeInvoiced: false,
    placementFeeReceived: false,
    motivations: 'Strong desire to work in emergency care internationally.',
    questions: 'How many retakes are allowed?',
    notesFlags: 'OET Writing score below threshold. Retake scheduled for January 2025.',
    source: 'Career Fair',
    sourceRecord: 'CF-2024-012',
    communicationLog: '2024-03-30: Application received. 2024-05-05: Interview. 2024-10-12: OET failed - writing below threshold. 2024-11-10: Retake plan discussed.',
  },
];
