import { AcquisitionSource, OutreachLead } from '@/types/acquisition';

export const mockAcquisitionSources: AcquisitionSource[] = [
  // Organisations
  {
    id: 'org-1',
    name: 'Netcare Hospital Group',
    type: 'Organisation',
    contactPerson: 'Dr. Sarah van der Merwe',
    contactEmail: 'sarah.vdm@netcare.co.za',
    status: 'Active',
    leadsGenerated: 24,
    conversionRate: 42,
    lastContact: '2024-11-15',
    notes: 'Key partner for ICU nurses. MOU signed for 2024-2025 recruitment cycle.',
  },
  {
    id: 'org-2',
    name: 'Life Healthcare',
    type: 'Organisation',
    contactPerson: 'James Mthembu',
    contactEmail: 'j.mthembu@lifehealthcare.co.za',
    status: 'Active',
    leadsGenerated: 18,
    conversionRate: 33,
    lastContact: '2024-11-10',
    notes: 'Strong pipeline of paediatric and general surgery nurses.',
  },
  {
    id: 'org-3',
    name: 'Mediclinic International',
    type: 'Organisation',
    contactPerson: 'Lindiwe Khumalo',
    contactEmail: 'l.khumalo@mediclinic.co.za',
    status: 'Prospective',
    leadsGenerated: 5,
    conversionRate: 20,
    lastContact: '2024-10-28',
    notes: 'Initial discussions held. Awaiting HR approval for formal partnership.',
  },
  {
    id: 'org-4',
    name: 'Stellenbosch Nursing Agency',
    type: 'Organisation',
    contactPerson: 'Pieter Botha',
    contactEmail: 'pieter@stellnursing.co.za',
    status: 'Inactive',
    leadsGenerated: 8,
    conversionRate: 12,
    lastContact: '2024-06-20',
    notes: 'Partnership paused. Re-evaluate in Q1 2025.',
  },
  // Referral Network
  {
    id: 'ref-1',
    name: 'SANC Alumni Network',
    type: 'Referral',
    contactPerson: 'Thandi Naidoo',
    contactEmail: 'thandi@sancalumni.org.za',
    status: 'Active',
    leadsGenerated: 31,
    conversionRate: 48,
    lastContact: '2024-11-18',
    notes: 'Top performing referral channel. Incentive programme active.',
  },
  {
    id: 'ref-2',
    name: 'UK-SA Nurse Bridge Programme',
    type: 'Referral',
    contactPerson: 'David Osei',
    contactEmail: 'david.osei@nursebridgeuk.com',
    status: 'Active',
    leadsGenerated: 14,
    conversionRate: 57,
    lastContact: '2024-11-12',
    notes: 'High quality referrals. Nurses often pre-qualified for UK placement.',
  },
  {
    id: 'ref-3',
    name: 'Cape Town Nursing College',
    type: 'Referral',
    contactPerson: 'Prof. Amina Patel',
    contactEmail: 'a.patel@ctnc.ac.za',
    status: 'Active',
    leadsGenerated: 22,
    conversionRate: 36,
    lastContact: '2024-11-05',
    notes: 'Academic partner. Final year students referred for early pipeline entry.',
  },
  {
    id: 'ref-4',
    name: 'Gauteng Private Hospitals Alliance',
    type: 'Referral',
    contactPerson: 'Sipho Mazibuko',
    contactEmail: 'sipho@gpha.co.za',
    status: 'Prospective',
    leadsGenerated: 3,
    conversionRate: 0,
    lastContact: '2024-10-22',
    notes: 'New contact. Meeting scheduled for November to discuss referral terms.',
  },
  // Community Channels
  {
    id: 'com-1',
    name: 'SA Nurses Abroad WhatsApp Group',
    type: 'Community',
    contactPerson: 'Nolwazi Mkhize',
    contactEmail: 'nolwazi.mkhize@gmail.com',
    status: 'Active',
    leadsGenerated: 45,
    conversionRate: 28,
    lastContact: '2024-11-20',
    notes: '2,400+ members. Weekly job postings generate consistent leads.',
  },
  {
    id: 'com-2',
    name: 'International Nursing Careers Facebook Group',
    type: 'Community',
    contactPerson: 'Rebecca Molefe',
    contactEmail: 'r.molefe@propela.co.za',
    status: 'Active',
    leadsGenerated: 38,
    conversionRate: 22,
    lastContact: '2024-11-19',
    notes: '5,600 members. Organic reach through shared success stories.',
  },
  {
    id: 'com-3',
    name: 'NurseConnect Forum',
    type: 'Community',
    contactPerson: 'Admin Team',
    contactEmail: 'admin@nurseconnect.co.za',
    status: 'Active',
    leadsGenerated: 19,
    conversionRate: 31,
    lastContact: '2024-11-08',
    notes: 'Sponsored posts and Q&A sessions drive engagement.',
  },
  {
    id: 'com-4',
    name: 'Nursing Careers SA Telegram',
    type: 'Community',
    contactPerson: 'Blessing Adeyemi',
    contactEmail: 'blessing@nursecareers.co.za',
    status: 'Prospective',
    leadsGenerated: 7,
    conversionRate: 14,
    lastContact: '2024-09-30',
    notes: 'Growing channel. Testing engagement with introductory content.',
  },
  // Events
  {
    id: 'evt-1',
    name: 'SA Nursing Career Fair 2024',
    type: 'Event',
    contactPerson: 'Event Coordinator',
    contactEmail: 'events@sanursingfair.co.za',
    status: 'Active',
    leadsGenerated: 52,
    conversionRate: 35,
    lastContact: '2024-11-01',
    notes: 'Annual event. Propela had a booth and presentation slot. Excellent ROI.',
  },
  {
    id: 'evt-2',
    name: 'International Healthcare Recruitment Conference',
    type: 'Event',
    contactPerson: 'Margaret Thompson',
    contactEmail: 'm.thompson@ihrc.org',
    status: 'Active',
    leadsGenerated: 16,
    conversionRate: 44,
    lastContact: '2024-10-15',
    notes: 'UK-based conference. Good source of employer connections and nurse awareness.',
  },
  {
    id: 'evt-3',
    name: 'Durban Health Sciences Open Day',
    type: 'Event',
    contactPerson: 'Dr. Nokuthula Zulu',
    contactEmail: 'n.zulu@dut.ac.za',
    status: 'Prospective',
    leadsGenerated: 9,
    conversionRate: 22,
    lastContact: '2024-09-12',
    notes: 'University event. Good for early-career pipeline. Next event Feb 2025.',
  },
  {
    id: 'evt-4',
    name: 'OET Preparation Workshop Series',
    type: 'Event',
    contactPerson: 'Propela Events Team',
    contactEmail: 'events@propela.co.za',
    status: 'Active',
    leadsGenerated: 28,
    conversionRate: 61,
    lastContact: '2024-11-16',
    notes: 'Monthly workshops. Highest conversion rate. Attendees are pre-motivated.',
  },
];

export const mockOutreachLeads: OutreachLead[] = [
  {
    id: 'lead-1',
    sourceId: 'org-1',
    sourceName: 'Netcare Hospital Group',
    nurseFullName: 'Ayanda Sithole',
    stage: 'Contacted',
    contactDate: '2024-11-18',
    followUpDate: '2024-11-25',
    notes: 'Initial email sent with programme overview.',
  },
  {
    id: 'lead-2',
    sourceId: 'ref-1',
    sourceName: 'SANC Alumni Network',
    nurseFullName: 'Lerato Moloi',
    stage: 'Interested',
    contactDate: '2024-11-10',
    followUpDate: '2024-11-22',
    notes: 'Expressed interest in UK placement. Requested more info on OET support.',
  },
  {
    id: 'lead-3',
    sourceId: 'com-1',
    sourceName: 'SA Nurses Abroad WhatsApp Group',
    nurseFullName: 'Kagiso Phiri',
    stage: 'Applied',
    contactDate: '2024-10-28',
    followUpDate: null,
    notes: 'Application submitted. CV under review.',
  },
  {
    id: 'lead-4',
    sourceId: 'evt-1',
    sourceName: 'SA Nursing Career Fair 2024',
    nurseFullName: 'Zinhle Buthelezi',
    stage: 'Converted',
    contactDate: '2024-09-15',
    followUpDate: null,
    notes: 'Successfully onboarded to Cohort 2024-B.',
  },
  {
    id: 'lead-5',
    sourceId: 'ref-2',
    sourceName: 'UK-SA Nurse Bridge Programme',
    nurseFullName: 'Mandisa Gcaba',
    stage: 'Interested',
    contactDate: '2024-11-14',
    followUpDate: '2024-11-24',
    notes: 'Scheduled video call to discuss programme details.',
  },
  {
    id: 'lead-6',
    sourceId: 'org-2',
    sourceName: 'Life Healthcare',
    nurseFullName: 'Thabo Moeletsi',
    stage: 'Contacted',
    contactDate: '2024-11-19',
    followUpDate: '2024-11-26',
    notes: 'Phone call made. Will follow up with email.',
  },
  {
    id: 'lead-7',
    sourceId: 'com-2',
    sourceName: 'International Nursing Careers Facebook Group',
    nurseFullName: 'Palesa Mahlangu',
    stage: 'Applied',
    contactDate: '2024-11-02',
    followUpDate: '2024-11-20',
    notes: 'Application received. Awaiting SANC verification.',
  },
  {
    id: 'lead-8',
    sourceId: 'evt-4',
    sourceName: 'OET Preparation Workshop Series',
    nurseFullName: 'Sibusiso Zwane',
    stage: 'Converted',
    contactDate: '2024-10-05',
    followUpDate: null,
    notes: 'Joined Cohort 2025-A after attending OET workshop.',
  },
  {
    id: 'lead-9',
    sourceId: 'ref-3',
    sourceName: 'Cape Town Nursing College',
    nurseFullName: 'Nokuthula Mabaso',
    stage: 'Lost',
    contactDate: '2024-10-20',
    followUpDate: null,
    notes: 'Accepted position locally. Not interested in international placement.',
  },
  {
    id: 'lead-10',
    sourceId: 'com-3',
    sourceName: 'NurseConnect Forum',
    nurseFullName: 'Dumebi Okafor',
    stage: 'Interested',
    contactDate: '2024-11-16',
    followUpDate: '2024-11-23',
    notes: 'Responded to forum post. Asking about financial support options.',
  },
];
